import IAccount from "./Iaccount";
import IEmoji from "./iemoji";
import IAttachment from "./iattachment";
import IMention from "./imention";
import ITag from "./itag";
import IApplication from "./iapplication";
import { Mastodon } from "../bot";
import { IStatusOption } from "../RequestInterfaces/POST/IStatusPost";

export default interface IStatus {
    id : number;
    uri : string;
    url : string;
    account : IAccount;
    inReplyToStatus : IStatus;
    inReplyToAccount : IAccount;
    rebloggedStatus : IStatus;
    content : string;
    createdAt : number;
    emojis : IEmoji[];
    repliesCount : number;
    reblogsCount : number;
    favouritesCount : number;
    reblogged : boolean;
    favourited : boolean;
    muted : boolean;
    sensetive : boolean;
    spoilerText : string;
    visibility : string;
    attachments : IAttachment[];
    mentions : IMention[];
    tags : ITag[];
    application : IApplication;
    language : string;
    pinned : boolean;
    client : Mastodon;
    reblogStatus : (reblog : boolean) => Promise<IStatus>;
    favouriteStatus : (faivourte : boolean) => Promise<IStatus>;
    pinStatus : (pin : boolean) => Promise<IStatus>;
    muteStatus : (mute : boolean) => Promise<IStatus>;
    reply : (options : IStatusOption) => Promise<IStatus>;
    deleteStatus : () => void;
}